apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-ing
  namespace: home
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - shananatestingdevops.xyz
      - www.shananatestingdevops.xyz  # Added the www version
      secretName: home-tls-secret  # Reference the TLS secret
  rules:
    - host: shananatestingdevops.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-svc
                port:
                  number: 80
    - host: www.shananatestingdevops.xyz  # Added rule for www host
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-svc
                port:
                  number: 80
