apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: wordpress
type: Opaque
data:
  root-password: cm9vdEBwYXNzd29yZA==  # base64 encoding of "root@password"
  db-password: ZGJAcGFzc3dvcmQ=         # base64 encoding of "db@password"