apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: voteapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: dockersamples/examplevotingapp_worker:latest
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: voteapp-configmap
              key: REDIS_HOST
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: voteapp-configmap
              key: POSTGRES_HOST
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: voteapp-configmap
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: voteapp-secret
              key: POSTGRES_PASSWORD
        resources:
          requests:
            memory: "512Mi"  # Minimum memory required
            cpu: "250m"      # Minimum CPU required

